/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BloodGroup = IDL.Variant({
  'B_Negative' : IDL.Null,
  'AB_Positive' : IDL.Null,
  'O_Positive' : IDL.Null,
  'A_Negative' : IDL.Null,
  'B_Positive' : IDL.Null,
  'AB_Negative' : IDL.Null,
  'A_Positive' : IDL.Null,
  'O_Negative' : IDL.Null,
});
export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'donor' : IDL.Null,
  'receiver' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'active' : IDL.Bool,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : UserRole,
  'lastDonationDate' : IDL.Opt(Time),
  'bloodGroup' : BloodGroup,
  'phone' : IDL.Text,
  'lastActive' : Time,
});
export const EmergencyRequest = IDL.Record({
  'requester' : IDL.Text,
  'city' : IDL.Text,
  'bloodGroup' : BloodGroup,
  'timestamp' : Time,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createEmergencyRequest' : IDL.Func([IDL.Text, BloodGroup, IDL.Text], [], []),
  'deactivateUser' : IDL.Func([IDL.Principal], [], []),
  'getAdminPanelData' : IDL.Func(
      [],
      [
        IDL.Record({
          'users' : IDL.Vec(UserProfile),
          'emergencyRequests' : IDL.Vec(EmergencyRequest),
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getDashboardData' : IDL.Func(
      [],
      [
        IDL.Record({
          'recentRequests' : IDL.Vec(EmergencyRequest),
          'nearbyDonors' : IDL.Vec(UserProfile),
          'totalDonors' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getSosImage' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func(
      [
        IDL.Text,
        UserRole,
        BloodGroup,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(Time),
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'smartDonorSearch' : IDL.Func(
      [BloodGroup, IDL.Text],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'uploadSosImage' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BloodGroup = IDL.Variant({
    'B_Negative' : IDL.Null,
    'AB_Positive' : IDL.Null,
    'O_Positive' : IDL.Null,
    'A_Negative' : IDL.Null,
    'B_Positive' : IDL.Null,
    'AB_Negative' : IDL.Null,
    'A_Positive' : IDL.Null,
    'O_Negative' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserRole = IDL.Variant({ 'donor' : IDL.Null, 'receiver' : IDL.Null });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'active' : IDL.Bool,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : UserRole,
    'lastDonationDate' : IDL.Opt(Time),
    'bloodGroup' : BloodGroup,
    'phone' : IDL.Text,
    'lastActive' : Time,
  });
  const EmergencyRequest = IDL.Record({
    'requester' : IDL.Text,
    'city' : IDL.Text,
    'bloodGroup' : BloodGroup,
    'timestamp' : Time,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createEmergencyRequest' : IDL.Func(
        [IDL.Text, BloodGroup, IDL.Text],
        [],
        [],
      ),
    'deactivateUser' : IDL.Func([IDL.Principal], [], []),
    'getAdminPanelData' : IDL.Func(
        [],
        [
          IDL.Record({
            'users' : IDL.Vec(UserProfile),
            'emergencyRequests' : IDL.Vec(EmergencyRequest),
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getDashboardData' : IDL.Func(
        [],
        [
          IDL.Record({
            'recentRequests' : IDL.Vec(EmergencyRequest),
            'nearbyDonors' : IDL.Vec(UserProfile),
            'totalDonors' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getSosImage' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func(
        [
          IDL.Text,
          UserRole,
          BloodGroup,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(Time),
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'smartDonorSearch' : IDL.Func(
        [BloodGroup, IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'uploadSosImage' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };