/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BloodGroup = { 'B_Negative' : null } |
  { 'AB_Positive' : null } |
  { 'O_Positive' : null } |
  { 'A_Negative' : null } |
  { 'B_Positive' : null } |
  { 'AB_Negative' : null } |
  { 'A_Positive' : null } |
  { 'O_Negative' : null };
export interface EmergencyRequest {
  'requester' : string,
  'city' : string,
  'bloodGroup' : BloodGroup,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'age' : bigint,
  'active' : boolean,
  'city' : string,
  'name' : string,
  'createdAt' : Time,
  'role' : UserRole,
  'lastDonationDate' : [] | [Time],
  'bloodGroup' : BloodGroup,
  'phone' : string,
  'lastActive' : Time,
}
export type UserRole = { 'donor' : null } |
  { 'receiver' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createEmergencyRequest' : ActorMethod<
    [string, BloodGroup, string],
    undefined
  >,
  'deactivateUser' : ActorMethod<[Principal], undefined>,
  'getAdminPanelData' : ActorMethod<
    [],
    {
      'users' : Array<UserProfile>,
      'emergencyRequests' : Array<EmergencyRequest>,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getDashboardData' : ActorMethod<
    [],
    {
      'recentRequests' : Array<EmergencyRequest>,
      'nearbyDonors' : Array<UserProfile>,
      'totalDonors' : bigint,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<
    [string, UserRole, BloodGroup, string, string, bigint, [] | [Time]],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'smartDonorSearch' : ActorMethod<[BloodGroup, string], Array<UserProfile>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];